### ISSUE TITLE
add a highlight in the navigation where currently opened document is in hierachry

### ISSUE THREAD

**Issue by jensbri** [UoA-eResearch/cer-documentation#28]

**Comment by jensbri** [comment]
![Uploading Screenshot 2023-11-29 at 11.52.09 AM.jpg…]()


similar to this one: 

https://cdn.folge.me/export-examples/rich_example.html#step-2

**Comment by jensbri** [comment]
Overrides of the theme seem to be best suited.
But Codelab already does occupy that space.
How to include both simultaneously isn't clear yet.

Here someone did something similar: https://github.com/squidfunk/mkdocs-material/discussions/4144#discussioncomment-3182585

And this is the relevant part of the mkdocs material documentation: https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure

**Comment by neon-ninja** [comment]
duplicate of https://github.com/UoA-eResearch/cer-documentation/issues/3?

**Comment by neon-ninja** [comment]
I think https://github.com/UoA-eResearch/cer-documentation/commit/894ad0b937b10699b6419ae31ab89246323fe153 should fix this? Or do you want a ➡️ or a → in there too? https://www.i2symbol.com/symbols/arrows

**Comment by jensbri** [comment]
Brilliant. Thank you!
